### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by rock-the-vote**

### CODE REVIEW

**Comment by rock-the-vote** [comment]
This all good to push out Alex?

**Comment by amekelburg** [comment]
@rock-the-vote I made a format fix to one of the files. I've merged this into the CSV updates branch so you can preview these changes on staging. If that looks good, you can merge this pull request to prod to deploy it.

**Comment by rock-the-vote** [comment]
is {registration_url} available to use inside abr / deadline_passed_instructions ? Maybe that's breaking it?

**Comment by amekelburg** [comment]
@rock-the-vote nope. Can you change it to a static value?

**Comment by rock-the-vote** [comment]
%{url} won't work either? Ideally it's dynamic so partner id 1234 absentee goes to a partner id 1234 registration.
(fine if we do static for now but should prob change)

**Comment by amekelburg** [comment]
@rock-the-vote no, there's a code change needed to specify what interpolation values to pass into that specific string. Can you create an asana task for that?

I've merged this into the CSV updates branch so it should be reviewable on staging.

**Pull request merged**
